const nodes = {
  alice: {
    hostname: "alice-lnd.sphinx:38881",
    password: "alice12345",
    mnemonic: [
      "above",
      "hair",
      "trigger",
      "live",
      "innocent",
      "monster",
      "surprise",
      "discover",
      "art",
      "broccoli",
      "cable",
      "balcony",
      "exclude",
      "maple",
      "luggage",
      "dragon",
      "erosion",
      "basic",
      "census",
      "earn",
      "ripple",
      "gossip",
      "record",
      "monster",
    ],
  },
  bob: {
    hostname: "bob-lnd.sphinx:38882",
    password: "bob12345",
    mnemonic: [
      "monster",
      "above",
      "hair",
      "trigger",
      "live",
      "innocent",
      "monster",
      "surprise",
      "discover",
      "art",
      "broccoli",
      "cable",
      "balcony",
      "exclude",
      "maple",
      "luggage",
      "dragon",
      "erosion",
      "basic",
      "census",
      "earn",
      "ripple",
      "gossip",
      "record",
    ],
  },
  carol: {
    hostname: "carol-lnd.sphinx:38883",
    password: "carol12345",
    mnemonic: [
      "record",
      "monster",
      "above",
      "hair",
      "trigger",
      "live",
      "innocent",
      "monster",
      "surprise",
      "discover",
      "art",
      "broccoli",
      "cable",
      "balcony",
      "exclude",
      "maple",
      "luggage",
      "dragon",
      "erosion",
      "basic",
      "census",
      "earn",
      "ripple",
      "gossip",
    ],
  },
  dave: {
    hostname: "dave-lnd.sphinx:38884",
    password: "dave12345",
    mnemonic: [
      "gossip",
      "record",
      "monster",
      "above",
      "hair",
      "trigger",
      "live",
      "innocent",
      "monster",
      "surprise",
      "discover",
      "art",
      "broccoli",
      "cable",
      "balcony",
      "exclude",
      "maple",
      "luggage",
      "dragon",
      "erosion",
      "basic",
      "census",
      "earn",
      "ripple",
    ],
  },
};

module.exports = {
  nodes,
};
