const macpath = ".lnd/data/chain/bitcoin/regtest/admin.macaroon";

const nodes = {
  bob: {
    alias: "bob",
    hostname: "bob-lnd.sphinx:38882",
    password: "bob12345",
    type: "lnd",
    macaroon: "/bob/" + macpath,
    channels: [
      {
        host: "dave-lnd.sphinx:9735",
        pubkey:
          "030841d1519f19c68e80efc5ef5af3460ca4bfa17486fda9baca878b9ef255358f",
      },
    ],
    mnemonic: [
      "above",
      "street",
      "spoon",
      "mercy",
      "shoot",
      "mammal",
      "color",
      "comic",
      "distance",
      "myself",
      "buyer",
      "response",
      "senior",
      "timber",
      "attract",
      "neither",
      "half",
      "laundry",
      "ethics",
      "swarm",
      "will",
      "boss",
      "spoil",
      "genius",
    ],
  },
  dave: {
    alias: "dave",
    type: "lnd",
    hostname: "dave-lnd.sphinx:38884",
    password: "dave12345",
    macaroon: "/dave/" + macpath,
    mnemonic: [
      "able",
      "stuff",
      "magic",
      "beach",
      "ankle",
      "exotic",
      "blood",
      "capital",
      "motor",
      "crouch",
      "once",
      "pigeon",
      "awake",
      "same",
      "ill",
      "crane",
      "write",
      "resource",
      "interest",
      "rail",
      "cigar",
      "duty",
      "body",
      "outdoor",
    ],
  },
};

module.exports = {
  nodes,
};
